### ISSUE TITLE
MacOS "ytfzf -H" "/usr/local/bin/ytfzf: line 596: tac: command not found"

### ISSUE THREAD

**Issue by petanecek** [pystardust/ytfzf#125]
MacOS "ytfzf -H" "/usr/local/bin/ytfzf: line 596: tac: command not found"

Since there is no "tac" in MacOS, replacing line number 596
hist_data="$(**tac** "$history_file")"
with
hist_data="$(**tail -r** "$history_file")"
fix the issue.

Also there is "tac" in line number 534, but I'm not sure if fixing this will brake the functionality or not.
Could you please test it?
Thanks!

**Comment by petanecek** [comment]
If the above is not possible, then you should install **coreutils**

_brew install coreutils_
or
_port install coreutils_

then run **which** to get fullpath to the "tac" binary
_which gtac_

and make new softlink named "tac"
for example:
_sudo ln -s /opt/local/bin/gtac /opt/local/bin/tac_

**Comment by pystardust** [comment]
Both `tac`s that you have mentioned are not very important functionaly. The one on line 534 is for reversing the list of formats, so that you. And the one on 596 is to reverse the history file before piping into fzf. So that the entries of the history menu are in the latest order you have wated them in.

`tail -r`, the option `-r`doesn't seem to be available in `GNU coreutils 8.32`. We will need to look for another tool.

**Comment by petanecek** [comment]
looks ok to me, let's get rid of the **tac**, **tail -r** & **coreutils**
