### ISSUE TITLE
[Request] PornHub fork?

### ISSUE THREAD

**Issue by Ramiferous** [pystardust/ytfzf#147]
So the real question on everybody's mind is, can this be forked to a PornHub version...

phfzf anyone?

**Comment by pystardust** [comment]
Im sorry there are no plans for adult sites. We are planning on having other video/anime platforms

**Comment by Ramiferous** [comment]
Oh well, it was worth asking ;)

**Comment by cybarspace** [comment]
I mean, you can port it yourself if you're ***that*** interested.

*Personal opinion: Hanime > PH*

**Comment by paniash** [comment]
Quick question though, since ytfzf scrapes videos from youtube, technically, it can be used to scrape from any video platform right? Or are there certain video sites that don't allow scraping?

**Comment by cybarspace** [comment]
> are there certain video sites that don't allow scraping?

It's less of not allowing scraping as opposed to making it insanely difficult. Take pirated anime sites for example (which you shouldn't visit btw, just saying), they kind of "encapsulate" the videos so that you can't get their URL from the search results page. You'll need to visit the page of each different episode and even then most of them use a different CDN so good luck figuring out how to get their URL. It's usually something random and cryptic and inconsistent, unlike YouTube videos which always have a 11-character video ID.

**Comment by Ramiferous** [comment]
> Quick question though, since ytfzf scrapes videos from youtube, technically, it can be used to scrape from any video platform right?

All I know is that `youtube-dl` works with PH so I just thought it would be an easy fork? I did try to edit the script myself but I couldn't get it working.
