### ISSUE TITLE
Get the output

### ISSUE THREAD

**Issue by microo8** [pystardust/ytfzf#237]
Is there a way to get just the output of the search? With the link, title and the thumbnail url?

I would like to feed the result to a gui app to see all the thumbnails and click on the video.

**Comment by Euro20179** [comment]
currently no, however, it is not that hard to add yourself at least in json form
in the function `scrape_yt`, after `videos_json` is defined you can add this line
(videos_json is defined at about line 681)

```sh
printf "%s" "$videos_json"
```
and that will print all the json results
or if you wanted a file:
```sh
printf "%s" "$videos_json" > whatever_file_name.json
```

you'll need to make the link yourself, because the json only has the videoId,
the link is easy to make
`https://www.youtube/com/watch?v={videoId}`

or if you want the data from youtube directly
```sh
printf "%s" "$yt_html" > the_file_to_write_to.json
```
however since that's the data from youtube it is not formatted into a small json file

also a heads up: livestreams have duration, views, and date as null

**Comment by microo8** [comment]
thank you
