### ISSUE TITLE
Would it be possible to see the comments?

### ISSUE THREAD

**Issue by ondrej256** [pystardust/ytfzf#34]
I have the habit of reading through the comments after watching a video.
Would it be possible to add this option? Perhaps put the comments into stout or a file? That would be a real game-changer for me. Thanks for the AMAZING work!

**Comment by pystardust** [comment]
I will add this to the todo. 
I think it's easy to get the  parent comments but gets harder to get the nested ones.

**Comment by pystardust** [comment]
I have added this to the todo

**Comment by p1839251** [comment]
I guess this feature has not yet been implemented yet.
So one more vote for this. :)
This is the only reason why I sometimes still have to watch YouTube in the browser.

**Comment by Euro20179** [comment]
I have an idea of how this would work, basically we'd have something called `scrape_selection` that happens before the video is played, and it would scrape the selections.
However I believe the best way to format the output of the theoretical `scrape_selection` would be json format, so if we scraped a youtube video it might look something like this

```json
{
    "likes": 777,
    "dislikes": null,
    "comments": [
        {
            "author": "Euro20179",
            "text": "very epic comment",
            "likes": 40,
            "dislikes": null
        }
    ]
}
```

It might have more info like `title`, `link`, etc....

The reason this is the best way is because the json can be easily parsed by a seperate program (maybe built into ytfzf maybe not, but probably at least as an addon) to read, and it can be parsed from other programs easily.

Not gonna lie the biggest challenge of this would be scraping the website in the first place, so it might take some time.

I'm not home right now, but when I get home I'll play around with this idea.

**Comment by ondrej256** [comment]
I am currently using [youtube-comment-downloader](https://github.com/egbertbouman/youtube-comment-downloader) which also works without Youtube API like ytfzf, so just scraping. However, it's written in Python, so rewriting it in shell script would take some work from someone more knowledgeable than me.
Alternatively, calling youtube-comment-downloader through ytfzf after watching a video may also be a possibility.

**Comment by Euro20179** [comment]
I have opted to use the invidious comments api, however that script provides, way, WAYYY more comments, so I may scrape youtube in the future, I'm too lazy to put in effort right now.

The way I implemented it is:
1. when you select a video, the script creates a fork that scrapes all selected video's comments
2. it writes that to a file in ~/.cache/ytfzf/{session_cache_dir}/post-scrape/comments-{video-id}.json
3. you can either read the json file OR run `ytfzf -c comments ~/.cache/ytfzf/{session_cache_dir}/post-scrape/comments-{video-id}.json

(sesion_cache_dir is a folder named with the format "<search>-<pid>", if there is no search or the search is longer than 200 chars, it will be SCRAPE-<scrape>)

I'm not planning on  making the way to read comments more user friendly as it can get messy quickly, but I might add a more user friendly way to [my wrapper script](https://github.com/euro20179/ytfzfctl)

I don't feel quite ready to push to upstream yet, but it works, and you can try it here:
```sh
git clone https://github.com/euro20179/ytfzf
cd ytfzf
git switch post-scrape
./ytfzf search
./ytfzf -c comments ~/.cache/ytfzf/<search>*/post-scrape/comments*
```

**Comment by Euro20179** [comment]
Ok, I have completely changed how this works as i have over engineered it. I left in the post_scrape thing because I think it can be cool. However to scrape comments now, you just do this `ytfzf -c comments link-to-youtube-video`
