### ISSUE TITLE
[QUESTION] What are the periods/dots at the end of listed videos? (And is it possible to remove them?)

### ISSUE THREAD

**Issue by jaredreardon** [pystardust/ytfzf#346]
As the title says, this is just a question about what exactly those periods or dots that appear at the ends of videos that are listed in ytfzf are. They appear in both the dmenu and normal fzf interfaces so I was wondering what they actually were. More importantly, I was wondering whether or not it was possible to remove them, perhaps to make room for other elements of the video's information, especially in the dmenu mode? Tried my best to picture what I'm talking about below (in the fzf mode at least since I couldn't screenshot the dmenu version).

![image](https://user-images.githubusercontent.com/67240033/126829433-6ea39cc7-e252-48da-93af-ae5e6dc065f5.png)

**Comment by pystardust** [comment]
when we provide lines to fzf it gives us a menu and the selected line is printed out. In ytfzf the selected line contains the title then a huge space then the id of the video. The id of the video is used to determine the url from the title.
Back searching the url from the title doesn't work quite well and is not well behaved. We would need some sort of a  unique ID that is searchable.
The .. appears due to this extra text to the right of the title
