### ISSUE TITLE
How to change tracks in playlist with mpv?

### ISSUE THREAD

**Issue by timsofteng** [pystardust/ytfzf#356]
Hello.
When I open playlist with -m flag I can't see mpv to change tracks. How can i do it?

**Comment by HexorCatZ** [comment]
from what i see, i cant change to another songs too.
because it ran `mpv` separately for every songs, i dont find any ways to skip or so.
my only ways is to spam the up error keys until it goes to the end of the song.
you may try the `shift + page up` too as it supposed to seek for 600 seconds. unless your songs is more than that long, it should skip it right away (i hope :disappointed_relieved:).
i cant test the `shift + page` up because on [st](https://st.suckless.org/) , it takes that as scroll up.

oh, take a look at [mpv shortcut keys](https://defkey.com/mpv-media-player-shortcuts), maybe you'll find something i didn't :smiley:

**Comment by Euro20179** [comment]
use < and >

**Comment by timsofteng** [comment]
> use < and >

works but its better to have abillity to see whole list and change song something
Like playlist in any common music player

**Comment by timsofteng** [comment]
> use < and >

works but its better to have abillity to see whole list and change song something
Like playlist in any common music player

**Comment by timsofteng** [comment]
> use < and >

works but its better to have abillity to see whole list and change song something
Like playlist in any common music player

**Comment by fromtheeast710** [comment]
You can use this mpv plugin https://github.com/jonniek/mpv-playlistmanager

**Comment by odnar-dev** [comment]
@timsofteng 
add this line to $HOME/.config/mpv/mpv.conf to always show mpv gui
`force-window=yes`
 
@Euro20179 i think this should be added as default behaviour, or at least be added to detach mode
if user run ytfzf with `--audio-only --detach` flags, there is no way to control the player

https://mpv.io/manual/master/#options-force-window

**Comment by Euro20179** [comment]
I agree that this should be default behavior, but I'm going to just add it to the rewrite we are working on.
