### ISSUE TITLE
Number of search results

### ISSUE THREAD

**Issue by ccellado** [pystardust/ytfzf#358]
I could not understand, how to get older videos?

For example searching lex fridman fetches only 33 results

**Comment by Euro20179** [comment]
currently you can't get more results than it already shows.

**Comment by odnar-dev** [comment]
hey @Euro20179 , i think you can make a function to get next page videos and saved theme in a tmp file
then use `fzf` `reload action` to dynamically update the video list without restarting fzf
and bind ctrl-n and ctrl-p to move between pages.

**Comment by Euro20179** [comment]
youtube doesn't give more results than are already shown.

**Comment by MoscowCassiopeia** [comment]
> youtube doesn't give more results than are already shown.
maybe you should try to parse alternative front end. Such as Invidious

**Comment by Euro20179** [comment]
> maybe you should try to parse alternative front end. Such as Invidious

Avoided this because scraping raw html is annoying without pup, discovered invidious' api yesterday and made #400 for the rewrite, it also allows for every filter to be used.
Using invidious seems to solve a lot of problems.
Currently though, it won't work for subscriptions/channels (for now) because some links for channels don't have the channel id in it.

**Comment by Euro20179** [comment]
use `--pages=` in the new version. (only for YT), for odysee use `--odysee-video-count=`
