### ISSUE TITLE
Show the youtube URL in the interface

### ISSUE THREAD

**Issue by novoid** [pystardust/ytfzf#427]
Hi,

I'm using `ytfzf -t -l` and I would love to have the original YouTube URL somewhere in the interface so that I may copy and paste it for sharing with social media or similar purposes.

Thanks!

**Comment by Euro20179** [comment]
the urls for the videos you're watching are stored in ~/.cache/ytfzf/<search>-<ytfzf-pid>/ids.

**Comment by Euro20179** [comment]
The ids for the videos you're watching are stored in `~/.cache/ytfzf/ids` (this is going to change in the next update to `~/.cache/ytfzf/<search>-<ytfzf-pid>/ids`), for now you could have something that looks like this

```sh
echo "https://www.youtube.com/watch?v=$(cat ~/.cache/ytfzf/ids | head -1)"
```

In the next update it'll store the full link instead of the video id

```sh
cat ~/.cache/ytfzf/*/ids
```

I also have a script I'm going to make public when I finish the update, where you could run `ytfzfctl video-info url`
