### ISSUE TITLE
Some Alt+Key won't work

### ISSUE THREAD

**Issue by p1839251** [pystardust/ytfzf#468]
Hi, Since I upgraded to version 2.0, some key combinations won't work.
https://github.com/pystardust/ytfzf/pull/288#issue-924138616
Have they been revoked?
Alt + t
Alt + o

But most importantly:
**Alt + s**

**Comment by Euro20179** [comment]
`alt-t` has been replaced with `alt-i` in 2.1, which shows all info, not just the title.
`alt-s` was readded in `2.1`

`alt-o` has been removed.

to add it back you can add this to your config

```sh
custom_shortcut_binds="alt-o"

handle_custom_keypress () {
    [ "$1" = "alt-d" ] && url_handler=$BROWSER
}
```

In the future I'm hoping to be able to make it so all you have to do is this.


```sh
custom_shortcut_binds="alt-o"

handle_keypress_alt_o () {
    url_handler=$BROWSER
}
```

Either way I'll probably add `alt-o` back because it'll be like 2 lines of code.

**Comment by p1839251** [comment]
`Alt+s` is working perfectly again
Thank you!
