### ISSUE TITLE
[BUG]: --type=channel throws parse error and claims "Nothing was scraped" after video is closed

### ISSUE THREAD

**Issue by egg4096** [pystardust/ytfzf#523]
### Describe the bug
After choosing a channel, ytfzf outputs `parse error: Invalid numeric literal at line 725, column 0`. After closing a video from this channel, `p failed to load website` and `Nothing was scraped` are thrown.

### To Reproduce
Enter `ytfzf --type=channel`
\*Search for a channel\*
\*Pick the right one\*
Throws `parse error: Invalid numeric literal at line 725, column 0`
\*Choose video\*
\*Close video\*
Throws
`> bestvideo+bestaudio/bestvideo/bestaudio	0	0	bestvideo	bestaudio`
`p failed to load website`
`Nothing was scraped`

### Expected behavior
No such outputs

### Screenshots
![image](https://user-images.githubusercontent.com/72076491/162303503-49ff6251-8c8a-4b54-96be-e8bb3cc530ca.png)

### Information
 - OS: Ubuntu 21.04 x86_64
 - Terminal: gnome-terminal
 - Ytfzf version: 2.2
- Output of `ls -l "$(which sh)"` (if your using fish: `ls -l (which sh)`):
`lrwxrwxrwx 1 root root 4 Jul 29  2021 /usr/bin/sh -> dash`

### Additional context
mpv with `no-terminal` setting, curl with `-S -s`

**Comment by Euro20179** [comment]
### Trying to reproduce

I ran `ytfzf --type=channel Explainging Computers` on version 2.2, with dash shell (like you), selected the first result, and first video, quit, and it worked as expected.

It's something else that is the problem here.

### More info that might help me

Do you have a ytfzf config, if so, what's in it? (I ran mine with an empty config)

What is the output of `jq --version`, if it's below 1.6, you could try compiling it yourself (https://github.com/stedolan/jq)

### Some ramblings

The fact that it's outputting what `ytdl_pref` is set to (`bestvideo+bestaudio/bestvideo/bestaudio 0 0 bestvideo bestaudio`), is weird to me because this is something that i would've added for debug purposes, and then removed.  However it could also be jq debug info.

### Some Suggestions

#### Suggestion 1

You should try running ytfzf from the development branch
```sh
git clone -b development https://github.com/pystardust/ytfzf
cd ytfzf
./ytfzf --type=channel explaining computers
```

#### Suggestion 2

Try (on ytfzf version 2.2):
1.  running `ytfzf --type=channel Explaining Computers`
2. select the channel
3. select the video
4. quit the video
5. cd to `~/.cache/ytfzf/Explaining Computers*/_home_*`
6. post the contents of `videos_json`

**Comment by egg4096** [comment]
jq is at 1.6
As for `~/.cache/ytfzf/`, only `search_hist` and `watch_hist` are in the directory after watching the video, this is something i've had happen before (and it's strangely inconsistent). The development branch isn't helping either, sadly. Could me using fish shell be a problem? 
###### PS: Who's printing `parse error: Invalid numeric literal at line 725, column 0`? And what file does line 725 belong to?

**Comment by Euro20179** [comment]
A couple things with your config
1. your video_player line is doing nothing I think what you want is something like this
```sh
video_player () {
    /usr/bin/celluloid "$@"
}
```
2. the broken line is search_again

I've made a push to development, if you update to development  branch
```sh
git clone -b https://github.com/pystardust/ytfzf
cd ytfzf
./ytfzf ...
```
it should work

The back button is broken unless loop (`-l`) is enabled.

**Comment by egg4096** [comment]
Thank you!
