### ISSUE TITLE
[Feature request]: Use athor invidious instances 

### ISSUE THREAD

**Issue by SamDc73** [pystardust/ytfzf#528]
### Problem
for some reasons https://vid.puffyan.us is a bit slow, i checked the other instances and some of theme were really faster to me (like https://yewtu.be/ for example)

### Feature
The ablity to add couple of instances in the conf file in case on of them is down or slow .

PS: I have checked the wiki and i find the -cU flag but i couldn't use other instance using it .

**Comment by Euro20179** [comment]
I believe this won't be possible in the sense you want, because detecting if a connection is slow and then switching to a different url is a bad idea, instead you should just use `invidious_instance='...' ytfzf ...` when you have a bad connection, I could however add `--invidious-instance` or `--ii` for convinience.

**Comment by Euro20179** [comment]
`--ii` is now available in version 2.4
