### ISSUE TITLE
Subscriptions not working anymore

### ISSUE THREAD

**Issue by devriesd** [pystardust/ytfzf#561]
### Before Making This Post
* [yes ] I have taken a look at both man pages, `ytfzf(1)` and `ytfzf(5)`

### What do you need help with?

'ytfzf -S' does not work for me anymore. Please help

**Comment by Euro20179** [comment]
What does it say?

What happens if you go to youtube.com

What happens when you use -cSI instead of -cS

**Comment by devriesd** [comment]
Im guessing the subs command line option had changed. Before I just had the S. 
Now its telling me:
"is not a scrapable link run:
to fix this warning" etc

Has the Subscriptions api changed recently?

**Comment by Euro20179** [comment]
> Im guessing the subs command line option had changed. Before I just had the S.

Yes, in version 2.0, `ytfzf` the script was rewritten to be more modular, in short: `-c` lets you pick a scraper `S` is the subscriptions scraper, `SI` is the same but uses invidious instead of youtube.

> Now its telling me:
> "is not a scrapable link run:
> to fix this warning" etc
> Has the Subscriptions api changed recently?

It's your choice whether or not to run the command, the warning is only there because ytfzf is essentially running the command for you, but sometimes the output can be wrong (even when run manually), so it can be good to manually check.

**Comment by devriesd** [comment]
Other than running the --channel-link option. How can I find the channel link in that format? 

Thanks for your help.

**Comment by Euro20179** [comment]
You have to find the id of the channel, and then the link will be in this format:
`https://youtube.com/channel/<id>/videos`
