### ISSUE TITLE
[BUG]: Search doesn't work with fzf, always prints "unknown option: {}""

### ISSUE THREAD

**Issue by justbispo** [pystardust/ytfzf#574]
### Describe the bug

Since a few weeks ago, a bug happens when I try to search from the terminal. Every time I search any term, it always prints `unknown option: {}"`. This happens with both the [ytfzf](https://aur.archlinux.org/packages/ytfzf) and [ytfzf-git](https://aur.archlinux.org/packages/ytfzf-git) packages from the AUR.
But using the dmenu option (`ytfzf -D`) works fine.

### To Reproduce

```
$ ytfzf
> test
Scraping YouTube (with https://invidious.weblibre.org) (test, pg: 1)
unknown option: {}"

$ ytfzf -t test
Scraping YouTube (with https://invidious.weblibre.org) (test, pg: 1)
unknown option: {}"
```

### Expected behavior

Open fzf to allow me to pick a video.

### Screenshots

![test](https://user-images.githubusercontent.com/38961424/190284398-3e85252e-9b9a-48ba-950a-75e84c3f35bf.png)

### Information
 - OS: Arch
 - Terminal: Alacritty and Kitty
 - Ytfzf version: 2.4.1 and 2.5.0
- Output of `ls -l "$(which sh)"` (if your using fish: `ls -l (which sh)`): `lrwxrwxrwx 1 root root 4 jan  8  2022 /usr/bin/sh -> bash`

### Additional context

Steps I've tried:
- Uninstalled and installed both ytfzf and ytfzf-git
- Used another terminal (Kitty)
- Used bash and fish
- Tried to search after deleting my custom config file

**Comment by Euro20179** [comment]
What's your `fzf` version?

**Comment by justbispo** [comment]
It's [0.33.0 (e03ac31)](https://archlinux.org/packages/community/x86_64/fzf/). By the way, I can start `fzf` with no issues, so I excluded `fzf` as the issue here.

**Comment by Euro20179** [comment]
fzf is the only thing that Ive found that gives that error message, it happens when running: `fzf {}`

Anyway your fzf version is the same as mine.

What do you have in your conifg (i know you tested without it, but just in case)?

**Comment by Euro20179** [comment]
Your config seems fine, I'm fairly certain the problem is with this section of the code in `interface_thumbnails`, but it looks perfectly fine.

```sh
jq -r '.[]|[.title,"'"$gap_space"'|"+.channel,"|"+.duration,"|"+.views,"|"+.date,"|"+.url]|join("\t")' < "$video_json_file" |
sort_video_data_fn |
SHELL="$(command -v sh)" fzf -m \
--preview "__is_fzf_preview=1 fzf_preview_side='$fzf_preview_side' scrape='$scrape' thumb_dir='$thumb_dir' YTFZF_PID='$YTFZF_PID' UEBERZUG_FIFO='$UEBERZUG_FIFO' $0 -U preview_img '$thumbnail_viewer' {} '$video_json_file'" \
--preview-window "$fzf_preview_side:50%:wrap" --layout=reverse --expect="$shortcut_binds" | set_keypress |
trim_url > "$selected_id_file"

```

Could you post the output of `sh -x ytfzf -t search` (warning that it will contain your username on your computer so if you want you can run `sh -x ytfzf 2>&1 | sed "s_$HOME_~_g"` instead, this will replace all instead of `/home/<user>` with ~)

**Comment by justbispo** [comment]
Here's the output of that command:
[https://hastebin.com/raw/xovoxusire](https://hastebin.com/raw/xovoxusire)

**Comment by Euro20179** [comment]
The problem is that your exporting `FZF_DEFAULT_OPTS=--no-height --layout=reverse --info=inline --preview=\"pistol {}\" --preview-window=right:50%:wrap --bind \"shift-up:preview-page-up,shift-down:preview-page-down\"` somewhere, so if you put `FZF_DEFAULT_OPTS=''` in your config file it should work.
